# Generated by Django 3.2.3 on 2021-05-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('df', 'Deferido'), ('in', 'Indeferido'), ('an', 'Em Analise')], default='an', max_length=2),
        ),
    ]
